services:
  api:
    image: "ethans333/pokemon-app_api:latest"
    ports:
      - "3000:3000"
  gui:
    image: "ethans333/pokemon-app_gui:latest"
    ports:
      - "80:80"
  db:
    image: "postgres:15"
    environment:
      POSTGRES_PASSWORD: password
    hostname: db-service
    ports:
      - "5432:5432"
  migrate:
    image: migrate/migrate
    volumes:
      - ./database/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:password@postgres:5432/pokemondb",
      "up"
    ]
    depends_on:
      - db
