services:
  api:
    image: "ethans333/pokemon-app_api:latest"
    ports:
      - "3000:3000"
  db:
    image: "postgres:15"
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
